Fix Python selection on Mac (#1263)
* respect custom tool names settings

* take custom tool names into account automatically

Uses ly_tool automatically in toolcommand by default, still allowing to
disable it via optional argument (no use case at the moment, though).

This allows toolcommand to know which tool is being called, regardless
of custom tool names, which is required for #1232 (Python selection on
macOS).

* macosx: make OS Python ignore PYTHON* env variables

Partially addresses #1232, solving the issue described in
https://github.com/frescobaldi/frescobaldi/issues/1232#issue-543283689:

Error using convert-ly in Frescobaldi 3.1 Mac app:
ImportError: Bad magic number in
/Volumes/Frescobaldi/Frescobaldi.app/Contents/Resources/site.pyc

* lilychooser: for toolcommands, keep only viable LilyPonds in the list

* macosx: choose Python based on actual requirements

Fixes #1232