Revert "Comply with PEP 621 license field format used by briefcase"
This reverts commit f1b2eb327026194165273fc222a488d205cfd3bb.

When building the source tarball, Hatch complains:
ValueError: Cannot specify both `file` and `text` in the `project.license` table