Fix crashes when changing sessions (#1207)
* Fix crashes when changing sessions

I'm not sure whether this is the ultimate fix,
but I haven't seen any of these crashes anymore:

Traceback (most recent call last):
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/menu.py",
line 115, in slotSessionsAction
manager.get(self.parentWidget()).startSession(action.objectName())
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/manager.py",
line 90, in startSession
active = sessions.loadSession(name)
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/__init__.py",
line 115, in loadSession
setCurrentSession(name)
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/__init__.py",
line 157, in setCurrentSession
app.sessionChanged(name)
File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py",
line 191, in emit
l.call(args, kwargs)
File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py",
line 308, in call
return self.func(obj, *args[self.argslice], **kwargs)
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/viewers/popplerwidget.py",
line 293, in slotSessionChanged
for v in session.value(files_key, ""):
TypeError: unable to convert a C++ 'QVariantList' instance to a Python
object

* The real fix for the previous commit

I can't explain to myself why this *seemed* to work.
After a few branch checkouts it doesn't do so anymore.
And the reason is pretty obvious: There is no `QStringList`
in the *Python* implementtion of Qt5 anymore (because there
is no `QString` anymore either).

This creates some hickups in the Python implementation of
`QSettings` and requires a workaround that had long been
implemented in
dd5e2e9b85faefa4187ff7e7d108d4b8610bb830
and is pretty widely used across the application.

So this should fix this one too.